#!/usr/bin/env python3
"""index.py — archivist: scan ORACLE Suite output folders into oracle-index.md.

Subcommands:
  scan [--root DIR]          rebuild oracle-index.md from every *Dossier.md found
  find <term> [--root DIR]   print index entries matching term (case-insensitive)

The index is a finding aid, never a source — cite the dossier it points to.
Never hand-edit oracle-index.md; re-run scan.
"""
import argparse, json, pathlib, re, sys
from datetime import datetime, timezone

DIRS = ["research", "market-research", "understanding", "decision", "factcheck",
        "critique", "action-plan", "runbook", "pipeline", "introspection", "recap"]
INDEX = "oracle-index.md"
LEDGER = "COORD-AGENTS.md"  # the SubagentStop hook's agent activity ledger
CANDIDATES = "compile/candidates.md"       # compile.py's repeated-work table
CANDIDATES_DATA = "compile/candidates.json"


def entries(root):
    out = []
    for d in DIRS:
        base = root / d
        if not base.is_dir():
            continue
        for p in sorted(base.rglob("*Dossier.md")):
            text = p.read_text(encoding="utf-8", errors="replace")
            lines = text.splitlines()
            title = next((l[2:].strip() for l in lines if l.startswith("# ")), p.stem)
            date = datetime.fromtimestamp(p.stat().st_mtime,
                                          timezone.utc).strftime("%Y-%m-%d")
            head, in_rmf = [], False
            for l in lines:
                if re.match(r"^#{1,3} .*Read Me First", l):
                    in_rmf = True
                    continue
                if in_rmf:
                    if l.startswith("#") or l.startswith("---"):
                        break
                    if l.strip():
                        head.append(l.strip()[:200])
                    if len(head) >= 6:
                        break
            out.append((d, title, date, p.relative_to(root).as_posix(), head))
    return out


def agent_ledger(root):
    """One index entry for the hook-written agent activity ledger, if present at
    the repo root. Returns (rel_path, entry_count) or None; degrades silently if
    the file is unreadable. entry_count = lines that start '- [' (one per agent)."""
    p = root / LEDGER
    if not p.is_file():
        return None
    try:
        text = p.read_text(encoding="utf-8", errors="replace")
    except Exception:
        return None
    count = sum(1 for l in text.splitlines() if l.startswith("- ["))
    return (p.relative_to(root).as_posix(), count)


def compile_candidates(root):
    """One index entry for compile.py's repeated-work table, if present. Returns
    (rel_path, ripe_count, total_count) or None; degrades silently when the table
    or its data file is missing or unreadable. Counts come from the JSON the same
    scan wrote — the markdown beside it is the reading copy."""
    p = root / CANDIDATES
    if not p.is_file():
        return None
    ripe = total = 0
    try:
        data = json.loads((root / CANDIDATES_DATA).read_text(encoding="utf-8"))
        cands = data.get("candidates", [])
        total = len(cands)
        ripe = sum(1 for c in cands if c.get("ripe"))
    except Exception:
        pass
    return (p.relative_to(root).as_posix(), ripe, total)


def cmd_scan(a):
    root = pathlib.Path(a.root).resolve()
    es = entries(root)
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%MZ")
    buf = ["# ORACLE index — generated by archivist; do not hand-edit (re-run scan)",
           f"Last scan: {now} · {len(es)} dossier(s)", ""]
    for d, title, date, rel, head in es:
        buf.append(f"### {title} — {date}")
        buf.append(f"folder: {d} · path: {rel}")
        buf.extend(head)
        buf.append("")
    led = agent_ledger(root)
    suffix = ""
    if led is not None:
        rel, count = led
        buf.append(f"### agent activity ledger — {count} entr{'y' if count == 1 else 'ies'}")
        buf.append(f"folder: (repo root) · path: {rel}")
        buf.append("agent activity ledger — which agents ran, what each concluded; "
                   "entries point at full transcripts")
        buf.append("")
        suffix = f" + agent ledger ({count})"
    cc = compile_candidates(root)
    if cc is not None:
        rel, ripe, total = cc
        buf.append(f"### compile candidates — {ripe} ripe of {total}")
        buf.append(f"folder: compile · path: {rel}")
        buf.append("compile candidates — repeated work the estate has recorded; "
                   "ripe rows are ready to compile")
        buf.append("")
        suffix += f" + compile candidates ({ripe}/{total} ripe)"
    (root / INDEX).write_text("\n".join(buf) + "\n", encoding="utf-8")
    print(f"{root / INDEX}: {len(es)} entries{suffix}")


def cmd_find(a):
    root = pathlib.Path(a.root).resolve()
    p = root / INDEX
    if not p.exists():
        sys.exit(f"no {INDEX} at {root} — run: index.py scan")
    blocks = p.read_text(encoding="utf-8").split("\n### ")
    hits = [b for b in blocks[1:] if a.term.lower() in b.lower()]
    if not hits:
        print(f"no index entries match {a.term!r} (index may be stale — re-scan)")
        return
    for b in hits:
        print("### " + b.strip() + "\n")


def main():
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="cmd", required=True)
    s = sub.add_parser("scan")
    s.add_argument("--root", default=".")
    s.set_defaults(f=cmd_scan)
    f = sub.add_parser("find")
    f.add_argument("term")
    f.add_argument("--root", default=".")
    f.set_defaults(f=cmd_find)
    a = ap.parse_args()
    a.f(a)


if __name__ == "__main__":
    main()
